import Foundation
import Testing

/// The art pipeline's four rosters name the same importers (0.7.5, A027).
///
/// **They had already drifted, twice, and nothing said so.** `import-stamp-art.py`
/// was in `rasterize-icons.sh`'s roster from 0.6.4 and never in `verify-art.py`'s
/// `IMPORTERS`, so `StampArt` was generated by `npm run icons` and unverifiable by
/// `npm run icons:verify` for two releases. `import-logo-art.py` shipped in 0.7.5
/// (A5) in *neither*, plus no `package.json` script — the screensaver wordmark was
/// reproducible from `art/icons/dvd/` only by someone who knew the file existed and
/// ran it by hand. Both are the same fault: a roster is a hand-kept list, and a
/// hand-kept list of files is exactly what goes stale when a sixth file lands.
///
/// So the list of importers *on disk* is the authority here, and the three places
/// that enumerate them are checked against it. Adding a seventh importer fails this
/// suite until it is wired everywhere, which is the whole point — the alternative is
/// finding out two releases later, as above.
///
/// **Why a Swift test for shell and Python.** It is the only gate that runs on every
/// push. `npm run icons` needs network access and `rsvg-convert`; `icons:verify`
/// needs Pillow; neither runs in CI. `swift test` does, on every branch. The same
/// argument that put `assertAssetsExist` in the generator rather than in
/// `verify-art.py` puts this here rather than in either script. Reached through
/// `#filePath` exactly as `LogoLayerTests` reaches the wordmark PNGs.
@Suite("Art pipeline rosters")
struct ArtPipelineRosterTests {
    /// `Tests/VinodexCoreTests/<this file>` -> the package root.
    private static var repoRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    private static func read(_ components: String...) throws -> String {
        var url = repoRoot
        for component in components { url.appendPathComponent(component) }
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Every `"..."` run in `text`, in order.
    ///
    /// Enough of a parser for the shapes involved — a Python tuple of literals, a
    /// `DIRS = (...)` line, an `output_dir(ROOT, "X")` call — and it needs no regex
    /// engine, which keeps the test identical on Linux and Darwin.
    private static func quoted(_ text: String) -> [String] {
        text.split(separator: "\"", omittingEmptySubsequences: false)
            .enumerated()
            .filter { $0.offset % 2 == 1 }
            .map { String($0.element) }
    }

    /// The text between the first `open` at or after `from` and the next `close`.
    private static func slice(_ text: String, from marker: String, to close: Character) -> String? {
        guard let start = text.range(of: marker) else { return nil }
        let rest = text[start.upperBound...]
        guard let end = rest.firstIndex(of: close) else { return nil }
        return String(rest[..<end])
    }

    // MARK: - The authority

    /// `scripts/import-*-art.py`, the set every roster below must reproduce.
    private static var importersOnDisk: Set<String> {
        get throws {
            let scripts = repoRoot.appendingPathComponent("scripts")
            let names = try FileManager.default.contentsOfDirectory(atPath: scripts.path)
            return Set(
                names.filter { $0.hasPrefix("import-") && $0.hasSuffix("-art.py") }
            )
        }
    }

    // MARK: - The three rosters

    /// The `for importer in ... ; do` line that runs the drawn-art half.
    private static var rasterizeRoster: Set<String> {
        get throws {
            let text = try read("scripts", "rasterize-icons.sh")
            guard let line = slice(text, from: "for importer in ", to: ";") else { return [] }
            return Set(line.split(whereSeparator: \.isWhitespace).map(String.init))
        }
    }

    /// `verify-art.py`'s `IMPORTERS` tuple.
    private static var verifyRoster: Set<String> {
        get throws {
            let text = try read("scripts", "verify-art.py")
            guard let tuple = slice(text, from: "IMPORTERS = (", to: ")") else { return [] }
            return Set(quoted(tuple))
        }
    }

    /// `verify-art.py`'s `DIRS` tuple — the bundle directories it diffs.
    private static var verifyDirs: Set<String> {
        get throws {
            let text = try read("scripts", "verify-art.py")
            guard let tuple = slice(text, from: "DIRS = (", to: ")") else { return [] }
            return Set(quoted(tuple))
        }
    }

    /// The npm scripts, by the command each one runs.
    private static var npmCommands: [String] {
        get throws {
            let data = try Data(contentsOf: repoRoot.appendingPathComponent("package.json"))
            let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
            let scripts = json?["scripts"] as? [String: String] ?? [:]
            return Array(scripts.values)
        }
    }

    // MARK: - Tests

    @Test("the importer set is not empty, so a parse failure cannot pass silently")
    func rostersParse() throws {
        let onDisk = try Self.importersOnDisk
        let rasterize = try Self.rasterizeRoster
        let verify = try Self.verifyRoster
        let dirs = try Self.verifyDirs
        #expect(onDisk.count >= 6, "found only \(onDisk.sorted()) under scripts/")
        #expect(!rasterize.isEmpty, "could not parse rasterize-icons.sh's roster")
        #expect(!verify.isEmpty, "could not parse verify-art.py's IMPORTERS")
        #expect(!dirs.isEmpty, "could not parse verify-art.py's DIRS")
    }

    @Test("rasterize-icons.sh runs every importer in scripts/")
    func rasterizeCoversAll() throws {
        let onDisk = try Self.importersOnDisk
        let roster = try Self.rasterizeRoster
        #expect(
            roster == onDisk,
            """
            rasterize-icons.sh's roster and scripts/import-*-art.py disagree — \
            not run: \(onDisk.subtracting(roster).sorted()), \
            named but absent: \(roster.subtracting(onDisk).sorted())
            """
        )
    }

    @Test("verify-art.py verifies every importer rasterize-icons.sh runs")
    func verifyMatchesRasterize() throws {
        let rasterize = try Self.rasterizeRoster
        let verify = try Self.verifyRoster
        #expect(
            rasterize == verify,
            """
            the two rosters have drifted (A027) — \
            generated but not verified: \(rasterize.subtracting(verify).sorted()), \
            verified but not generated: \(verify.subtracting(rasterize).sorted())
            """
        )
    }

    /// Each importer declares its bundle directory as `output_dir(<root>, "Name")`
    /// — the one call `ART_OUT` redirects — so the destinations are readable from
    /// the source rather than restated. `DIRS` must cover all of them, or an
    /// importer's output is regenerated into the temp tree and then never compared,
    /// which is the shape `StampArt` shipped in.
    @Test("verify-art.py's DIRS covers every importer's output directory")
    func verifyDirsCoverOutputs() throws {
        var declared: Set<String> = []
        for importer in try Self.importersOnDisk.sorted() {
            let text = try Self.read("scripts", importer)
            guard let call = Self.slice(text, from: "output_dir(", to: ")") else {
                Issue.record("\(importer) does not route its destination through art_common.output_dir")
                continue
            }
            guard let name = Self.quoted(call).last else {
                Issue.record("\(importer)'s output_dir call names no directory: \(call)")
                continue
            }
            declared.insert(name)
        }
        let dirs = try Self.verifyDirs
        #expect(
            declared.subtracting(dirs).isEmpty,
            "importers write directories verify-art.py never diffs: \(declared.subtracting(dirs).sorted())"
        )
        #expect(
            dirs.subtracting(declared).isEmpty,
            "verify-art.py's DIRS names directories no importer writes: \(dirs.subtracting(declared).sorted())"
        )
    }

    /// The per-importer convenience scripts. `npm run icons` chains all of them;
    /// these are how you re-run one while iterating on its art, and `import-logo-art`
    /// having none is half of why nothing noticed it was unwired.
    @Test("package.json exposes every importer as its own script")
    func npmScriptsCoverAll() throws {
        let commands = try Self.npmCommands
        for importer in try Self.importersOnDisk.sorted() {
            #expect(
                commands.contains { $0.contains(importer) },
                "no package.json script runs \(importer)"
            )
        }
        // The outline generator is not an importer — it writes *sources* under
        // `art/`, which `import-class-art.py` then converts — so it is outside
        // the four rosters above by construction. It still needs a way to be run
        // by someone who did not write it (0.8.0, A1).
        #expect(
            commands.contains { $0.contains("make-country-outlines.py") },
            "no package.json script runs the outline generator"
        )
    }

    // MARK: - The outline masters (0.8.0, A1)

    /// **Every country the catalog draws an outline for has an authored ring, and
    /// every authored ring is drawn.**
    ///
    /// This is the same two-way shape `assertOutlineCoverage` uses, one layer
    /// further back. That check asks "does this place have outline art"; this one
    /// asks "does that art have a master". Before A1 the answer for 28 of the 30
    /// was a PNG somebody drew, and there was nothing to check. Now the master is
    /// `scripts/country-outline-rings.py` and a 31st country reaching
    /// `countryShapeIcons` without a ring would produce an importer that reports
    /// a missing source — at art time, on somebody's laptop, rather than here.
    ///
    /// Failing both ways matters as much as it does there: a ring for a country
    /// the catalog no longer draws is dead data that the next reader will trust.
    @Test("every drawn outline has an authored ring, and every ring is drawn")
    func outlineRingsMatchTheManifest() throws {
        let manifest = try Data(
            contentsOf: Self.repoRoot
                .appendingPathComponent("Sources/VinodexCore/Resources/icons.json")
        )
        let json = try JSONSerialization.jsonObject(with: manifest) as? [String: Any]
        let shapes = json?["countryShapeIcons"] as? [String: String] ?? [:]
        #expect(!shapes.isEmpty, "icons.json carries no countryShapeIcons")

        let wanted = Set(shapes.values.map { $0.replacingOccurrences(of: "art:outline-", with: "") })

        // `FILENAME` is the ring file's own stem -> master-filename table. Parsed
        // rather than duplicated, exactly as the rosters above are.
        let ringSource = try Self.read("scripts", "country-outline-rings.py")
        guard let table = Self.slice(ringSource, from: "FILENAME = {", to: "}") else {
            Issue.record("could not parse FILENAME out of country-outline-rings.py")
            return
        }
        // Alternating key, filename across the quoted runs.
        let quoted = Self.quoted(table)
        var authored: [String: String] = [:]
        for pair in stride(from: 0, to: quoted.count - 1, by: 2) {
            authored[quoted[pair]] = quoted[pair + 1]
        }

        #expect(
            wanted.subtracting(authored.keys).isEmpty,
            "outlines the catalog draws with no authored ring: \(wanted.subtracting(authored.keys).sorted())"
        )
        #expect(
            Set(authored.keys).subtracting(wanted).isEmpty,
            "rings authored for outlines nothing draws: \(Set(authored.keys).subtracting(wanted).sorted())"
        )

        // And each one has produced its master. The importer's `SOURCE_FOR` looks
        // these up by name, so a rename here is a missing source there.
        for (stem, file) in authored.sorted(by: { $0.key < $1.key }) {
            let url = Self.repoRoot
                .appendingPathComponent("art/icons/countries")
                .appendingPathComponent(file)
            #expect(
                FileManager.default.fileExists(atPath: url.path),
                "\(stem): no master at art/icons/countries/\(file) — run `npm run outlines`"
            )
        }
    }
}
