import Foundation
import Testing
// The stamp roster (0.8.5, F1) is the first check here that compares a script
// against a *type* rather than against another script — `StampCatalog` and
// `BackPlateDecal` both live in Core, so the stems the app asks for can be read
// from the app rather than restated in a list this suite would then have to
// police as well.
@testable import VinodexCore

/// The art pipeline's four rosters name the same importers (0.7.5, A027).
///
/// **They had already drifted, twice, and nothing said so.** `import-stamp-art.py`
/// was in `rasterize-icons.sh`'s roster from 0.6.4 and never in `verify-art.py`'s
/// `IMPORTERS`, so `StampArt` was generated by `npm run icons` and unverifiable by
/// `npm run icons:verify` for two releases. `import-logo-art.py` shipped in 0.7.5
/// (A5) in *neither*, plus no `package.json` script — the screensaver wordmark was
/// reproducible from `art/icons/chrome/logo/` only by someone who knew the file existed and
/// ran it by hand. Both are the same fault: a roster is a hand-kept list, and a
/// hand-kept list of files is exactly what goes stale when a sixth file lands.
///
/// So the list of importers *on disk* is the authority here, and the three places
/// that enumerate them are checked against it. Adding a seventh importer fails this
/// suite until it is wired everywhere, which is the whole point — the alternative is
/// finding out two releases later, as above.
///
/// **Ten as of 0.8.2**, which is the suite earning its keep twice in one batch:
/// `import-footer-art.py` and `import-cartridge-art.py` landed together, and
/// each one had to be added to the rasteriser, to `IMPORTERS`, to `DIRS` and to
/// `package.json` before this went green. That is eight edits nobody would have
/// remembered from the shape of the task, which was "wire up some new art".
/// **Thirteen as of 0.8.9a**, and the two that landed together (`import-glyph-art.py`
/// and `import-vino-art.py`) each needed all six places, which is twelve edits
/// nobody would have remembered from the shape of the task — again "wire up some
/// new art". The same batch moved every master under `art/icons/` into
/// `entries/` and `chrome/`, which is a seventh place per importer and the one
/// this suite could not have caught: a source path is read at *import* time, so
/// a stale one fails loudly on the next `npm run icons` rather than silently.
/// `npm run icons:verify` is what proved that move inert — 379 files identical
/// before a single new asset was added.
///
/// There is a fifth place these two also needed — `PixelArtLoader.subdirectories`
/// — which this suite cannot see, because it lives in `VinodexUI`. That gap is
/// real and the clean `xtool` build is what covers it: a directory the loader
/// never searches yields a nil image, and nil images are silent.
///
/// **That last paragraph was wrong, and a sixth place has since appeared.** The
/// gap was not that `VinodexUI` is uncompilable here — this suite never compiles
/// anything it checks. It reads shell and Python off disk through `#filePath`,
/// and `EntryVisual.swift` is a text file by the same measure. The clean `xtool`
/// build does *not* cover it either: an unsearched directory yields nil, nil is
/// silent, and the build is green. The `Bundle layout` section below closes it,
/// and closes the sixth place with it — `Package.swift` now names each bundled
/// directory by hand (a codesign requirement, see there), which turns a list
/// that used to maintain itself into one more hand-kept roster of exactly the
/// kind this suite was written for. It had already drifted by three entries on
/// arrival.
///
/// **Why a Swift test for shell and Python.** It is the only gate that runs on every
/// push. `npm run icons` needs network access and `rsvg-convert`; `icons:verify`
/// needs Pillow; neither runs in CI. `swift test` does, on every branch. The same
/// argument that put `assertAssetsExist` in the generator rather than in
/// `verify-art.py` puts this here rather than in either script. Reached through
/// `#filePath` exactly as `LogoLayerTests` reaches the wordmark PNGs.
@Suite("Art pipeline rosters")
struct ArtPipelineRosterTests {
    /// `Tests/VinodexCoreTests/<this file>` -> the package root.
    private static var repoRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    private static func read(_ components: String...) throws -> String {
        var url = repoRoot
        for component in components { url.appendPathComponent(component) }
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Every `"..."` run in `text`, in order.
    ///
    /// Enough of a parser for the shapes involved — a Python tuple of literals, a
    /// `DIRS = (...)` line, an `output_dir(ROOT, "X")` call — and it needs no regex
    /// engine, which keeps the test identical on Linux and Darwin.
    ///
    /// It does **not** understand comments, and callers that read a heavily
    /// annotated list must account for that — see `loaderSearchPath`.
    private static func quoted(_ text: String) -> [String] {
        text.split(separator: "\"", omittingEmptySubsequences: false)
            .enumerated()
            .filter { $0.offset % 2 == 1 }
            .map { String($0.element) }
    }

    /// The text between the first `open` at or after `from` and the next `close`.
    private static func slice(_ text: String, from marker: String, to close: Character) -> String? {
        guard let start = text.range(of: marker) else { return nil }
        let rest = text[start.upperBound...]
        guard let end = rest.firstIndex(of: close) else { return nil }
        return String(rest[..<end])
    }

    // MARK: - The authority

    /// `scripts/import-*-art.py`, the set every roster below must reproduce.
    private static var importersOnDisk: Set<String> {
        get throws {
            let scripts = repoRoot.appendingPathComponent("scripts")
            let names = try FileManager.default.contentsOfDirectory(atPath: scripts.path)
            return Set(
                names.filter { $0.hasPrefix("import-") && $0.hasSuffix("-art.py") }
            )
        }
    }

    // MARK: - The three rosters

    /// The `for importer in ... ; do` line that runs the drawn-art half.
    private static var rasterizeRoster: Set<String> {
        get throws {
            let text = try read("scripts", "rasterize-icons.sh")
            guard let line = slice(text, from: "for importer in ", to: ";") else { return [] }
            return Set(line.split(whereSeparator: \.isWhitespace).map(String.init))
        }
    }

    /// `verify-art.py`'s `IMPORTERS` tuple.
    private static var verifyRoster: Set<String> {
        get throws {
            let text = try read("scripts", "verify-art.py")
            guard let tuple = slice(text, from: "IMPORTERS = (", to: ")") else { return [] }
            return Set(quoted(tuple))
        }
    }

    /// `verify-art.py`'s `DIRS` tuple — the bundle directories it diffs.
    private static var verifyDirs: Set<String> {
        get throws {
            let text = try read("scripts", "verify-art.py")
            guard let tuple = slice(text, from: "DIRS = (", to: ")") else { return [] }
            return Set(quoted(tuple))
        }
    }

    /// The npm scripts, by the command each one runs.
    private static var npmCommands: [String] {
        get throws {
            let data = try Data(contentsOf: repoRoot.appendingPathComponent("package.json"))
            let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
            let scripts = json?["scripts"] as? [String: String] ?? [:]
            return Array(scripts.values)
        }
    }

    // MARK: - Tests

    @Test("the importer set is not empty, so a parse failure cannot pass silently")
    func rostersParse() throws {
        let onDisk = try Self.importersOnDisk
        let rasterize = try Self.rasterizeRoster
        let verify = try Self.verifyRoster
        let dirs = try Self.verifyDirs
        #expect(onDisk.count >= 6, "found only \(onDisk.sorted()) under scripts/")
        #expect(!rasterize.isEmpty, "could not parse rasterize-icons.sh's roster")
        #expect(!verify.isEmpty, "could not parse verify-art.py's IMPORTERS")
        #expect(!dirs.isEmpty, "could not parse verify-art.py's DIRS")
    }

    @Test("rasterize-icons.sh runs every importer in scripts/")
    func rasterizeCoversAll() throws {
        let onDisk = try Self.importersOnDisk
        let roster = try Self.rasterizeRoster
        #expect(
            roster == onDisk,
            """
            rasterize-icons.sh's roster and scripts/import-*-art.py disagree — \
            not run: \(onDisk.subtracting(roster).sorted()), \
            named but absent: \(roster.subtracting(onDisk).sorted())
            """
        )
    }

    @Test("verify-art.py verifies every importer rasterize-icons.sh runs")
    func verifyMatchesRasterize() throws {
        let rasterize = try Self.rasterizeRoster
        let verify = try Self.verifyRoster
        #expect(
            rasterize == verify,
            """
            the two rosters have drifted (A027) — \
            generated but not verified: \(rasterize.subtracting(verify).sorted()), \
            verified but not generated: \(verify.subtracting(rasterize).sorted())
            """
        )
    }

    /// Each importer declares its bundle directory as `output_dir(<root>, "Name")`
    /// — the one call `ART_OUT` redirects — so the destinations are readable from
    /// the source rather than restated. `DIRS` must cover all of them, or an
    /// importer's output is regenerated into the temp tree and then never compared,
    /// which is the shape `StampArt` shipped in.
    @Test("verify-art.py's DIRS covers every importer's output directory")
    func verifyDirsCoverOutputs() throws {
        var declared: Set<String> = []
        for importer in try Self.importersOnDisk.sorted() {
            let text = try Self.read("scripts", importer)
            guard let call = Self.slice(text, from: "output_dir(", to: ")") else {
                Issue.record("\(importer) does not route its destination through art_common.output_dir")
                continue
            }
            guard let name = Self.quoted(call).last else {
                Issue.record("\(importer)'s output_dir call names no directory: \(call)")
                continue
            }
            declared.insert(name)
        }
        let dirs = try Self.verifyDirs
        #expect(
            declared.subtracting(dirs).isEmpty,
            "importers write directories verify-art.py never diffs: \(declared.subtracting(dirs).sorted())"
        )
        #expect(
            dirs.subtracting(declared).isEmpty,
            "verify-art.py's DIRS names directories no importer writes: \(dirs.subtracting(declared).sorted())"
        )
    }

    // MARK: - The bundle layout (merged from the Aug 5 Xcode/codesign branch)

    /// Directories that exist under `Sources/VinodexUI/Resources/`.
    private static var bundledDirectoriesOnDisk: Set<String> {
        get throws {
            var url = repoRoot
            for component in ["Sources", "VinodexUI", "Resources"] {
                url.appendPathComponent(component)
            }
            let names = try FileManager.default.contentsOfDirectory(
                at: url,
                includingPropertiesForKeys: [.isDirectoryKey]
            )
            return Set(
                names
                    .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }
                    .map(\.lastPathComponent)
            )
        }
    }

    /// `Package.swift`'s `VinodexUI` resource list, less the `Resources/` prefix
    /// each `.copy` path carries.
    ///
    /// Sliced from the `VinodexUI` target rather than the whole file, because
    /// `VinodexCore`'s list above it names eight JSON *files* by the same
    /// `.copy("Resources/...")` spelling and would otherwise be counted in.
    ///
    /// **Two slices, not one**, and the reason is worth writing down because the
    /// one-slice version parsed to an empty set and the empty set is what a
    /// silently-passing gate looks like. `slice(_:from:to:)` stops at the first
    /// closing character, and the first `]` after `name: "VinodexUI"` closes
    /// `dependencies: ["VinodexCore"]`, not the resource list. So this narrows to
    /// the target first and to `resources: [` second. The `!declared.isEmpty`
    /// assertion below is what caught it, and it is there for exactly this — the
    /// same reason `rostersParse` exists one section up.
    private static var packageResourceDirectories: Set<String> {
        get throws {
            let text = try read("Package.swift")
            // Everything from the target's name onward — no closing character,
            // because the first `)` after it belongs to a `.copy(...)` call
            // inside the very list being looked for.
            guard let name = text.range(of: "name: \"VinodexUI\"") else { return [] }
            let target = String(text[name.upperBound...])
            guard let list = slice(target, from: "resources: [", to: "]") else { return [] }
            return Set(
                quoted(list)
                    .filter { $0.hasPrefix("Resources/") }
                    .map { String($0.dropFirst("Resources/".count)) }
            )
        }
    }

    /// `PixelArtLoader.subdirectories`, as written in `EntryVisual.swift`.
    ///
    /// Parsed off disk for the reason every roster above is: the loader lives in
    /// `VinodexUI`, which no Linux gate can compile, and this suite's own header
    /// records that gap as real and uncovered. It is a text file either way.
    private static var loaderSearchPath: [String] {
        get throws {
            let text = try read("Sources", "VinodexUI", "EntryVisual.swift")
            guard let list = slice(text, from: "private static let subdirectories = [", to: "]") else { return [] }
            // **Keep only what can be a directory name.** `quoted` has no idea
            // what a comment is, and this is the most heavily annotated list in
            // the package — a paragraph per entry explaining why the order is
            // what it is. Prose about strings tends to quote them, and one of
            // those notes reads `so "first hit wins" stays a statement about
            // ordering`, which parses as a tenth search path. A directory name
            // here is a single bare word, so requiring that is enough to tell
            // the entries from the prose, and it fails loudly rather than
            // silently if a real entry ever stops looking like one.
            return quoted(list).filter { name in
                !name.isEmpty && name.allSatisfy { $0.isLetter || $0.isNumber }
            }
        }
    }

    /// Declared on the loader's search path but not yet drawn, so no directory
    /// exists and `.copy` would fail the build if `Package.swift` named one.
    ///
    /// A named exemption rather than a silent subtraction: the day either set is
    /// authored, the importer creates the directory, the equality below starts
    /// failing, and the fix is to add the `.copy` *and* delete the name from
    /// here. Both halves, which is what an exemption list is for.
    ///
    /// **Empty since 0.8.5 (F1), and that is the list working.** It held
    /// `StampArt` and `StickerArt` from the day it was written. Both were
    /// authored in this batch, both directories appeared, and the check at the
    /// bottom of `loaderSearchPathIsBundled` failed on exactly the two names —
    /// which is the entire reason an exemption is written as a two-way
    /// assertion rather than as a subtraction. Kept at zero entries rather than
    /// deleted: the next search path added ahead of its art needs somewhere to
    /// be declared, and a list that has been emptied once is a list somebody
    /// trusts.
    private static let unauthoredArtDirectories: Set<String> = []

    /// **Every bundled directory is declared, and nothing is declared twice over.**
    ///
    /// `Package.swift` used to say `.copy("Resources")` and pick up a new
    /// directory the moment an importer created one. The Aug 5 codesign fix had
    /// to stop doing that — a shallow iOS bundle whose root holds a folder named
    /// `Resources` is rejected by codesign — so the children are now listed by
    /// hand, and a hand-kept list of directories is precisely what this suite
    /// exists to police for scripts.
    ///
    /// It was already wrong when it arrived, through nobody's fault: `ButtonArt`
    /// (0.8.1), `FooterArt` and `CartridgeArt` (0.8.2) were being written on a
    /// batch branch while the list was written on another. A bundle missing them
    /// compiles, signs, installs and runs — and every drawn face, footer cap and
    /// cartridge silently falls back, because `PixelArtLoader` and `IconLoader`
    /// both return nil rather than throwing.
    @Test("every bundled resource directory is copied by Package.swift")
    func bundledArtDirectoriesAreRegistered() throws {
        let onDisk = try Self.bundledDirectoriesOnDisk
        let declared = try Self.packageResourceDirectories
        #expect(onDisk.count >= 10, "found only \(onDisk.sorted()) — did the slice parse?")
        #expect(!declared.isEmpty, "could not parse Package.swift's VinodexUI resource list")
        #expect(
            declared == onDisk,
            """
            Package.swift and Sources/VinodexUI/Resources/ disagree — \
            on disk but not bundled: \(onDisk.subtracting(declared).sorted()), \
            bundled but absent (this is a build error): \(declared.subtracting(onDisk).sorted())
            """
        )
    }

    /// **The loader searches only directories that will be in the bundle.**
    ///
    /// The other half of the same fault. A stem is looked up by walking this list,
    /// so a directory that ships but is never searched is art nobody can reach,
    /// and a directory that is searched but never ships is a lookup that always
    /// misses. Both are invisible at runtime.
    @Test("PixelArtLoader searches only directories that ship")
    func loaderSearchPathIsBundled() throws {
        let search = try Self.loaderSearchPath
        let declared = try Self.packageResourceDirectories
        #expect(search.count >= 8, "could not parse PixelArtLoader.subdirectories")

        for entry in search {
            // The prefix is the bug this whole merge was about: under the new
            // bundle layout `Resources/ButtonArt` resolves to nothing, and
            // `DexResources.url`'s fallback is a *root*-level lookup that cannot
            // find a nested file either. Nil, in silence, forever.
            #expect(
                !entry.hasPrefix("Resources/"),
                "PixelArtLoader searches '\(entry)' — the bundle has no Resources/ wrapper any more"
            )
            #expect(
                declared.contains(entry) || Self.unauthoredArtDirectories.contains(entry),
                "PixelArtLoader searches '\(entry)', which Package.swift does not bundle"
            )
        }

        // And the exemptions must still be exemptions: a directory that has been
        // drawn since this list was written is one Package.swift now has to name.
        let onDisk = try Self.bundledDirectoriesOnDisk
        for name in Self.unauthoredArtDirectories {
            #expect(
                !onDisk.contains(name),
                "\(name) now exists — bundle it in Package.swift and drop it from unauthoredArtDirectories"
            )
        }
    }

    /// **No stale `Resources/` prefix anywhere in the UI module.**
    ///
    /// The general form, swept textually, because the two tests above only see
    /// the lists — a one-off `DexResources.url(..., subdirectory: "Resources/X")`
    /// in a view body is reachable by neither. There were eleven such call sites
    /// before the merge and every one of them had to move.
    ///
    /// `VinodexCore` is deliberately not swept: its three JSON lookups still ask
    /// for `subdirectory: "Resources"` first and fall through to a bare
    /// `Bundle.module.url(forResource:withExtension:)`, which finds them because
    /// under the new layout those files sit at the bundle *root*. The art cannot
    /// use that trick — it is one level deeper — which is exactly why the fix had
    /// to touch the UI module and not this one.
    @Test("no VinodexUI lookup still asks for the Resources wrapper")
    func noPrefixedSubdirectoryLookupsSurvive() throws {
        let dir = Self.repoRoot
            .appendingPathComponent("Sources")
            .appendingPathComponent("VinodexUI")
        let files = try FileManager.default
            .contentsOfDirectory(atPath: dir.path)
            .filter { $0.hasSuffix(".swift") }
        #expect(files.count >= 20, "found only \(files.count) sources under Sources/VinodexUI")

        for file in files.sorted() {
            let text = try String(contentsOf: dir.appendingPathComponent(file), encoding: .utf8)
            let lines: [Substring] = text.split(separator: Character("\n"), omittingEmptySubsequences: false)
            for (offset, line) in lines.enumerated()
            where line.contains("subdirectory: \"Resources") && !line.contains("///") {
                Issue.record("\(file):\(offset + 1) still asks for the Resources/ wrapper: \(line.trimmingCharacters(in: .whitespaces))")
            }
        }
    }

    /// The per-importer convenience scripts. `npm run icons` chains all of them;
    /// these are how you re-run one while iterating on its art, and `import-logo-art`
    /// having none is half of why nothing noticed it was unwired.
    @Test("package.json exposes every importer as its own script")
    func npmScriptsCoverAll() throws {
        let commands = try Self.npmCommands
        for importer in try Self.importersOnDisk.sorted() {
            #expect(
                commands.contains { $0.contains(importer) },
                "no package.json script runs \(importer)"
            )
        }
        // The outline generator is not an importer — it writes *sources* under
        // `art/`, which `import-class-art.py` then converts — so it is outside
        // the four rosters above by construction. It still needs a way to be run
        // by someone who did not write it (0.8.0, A1).
        #expect(
            commands.contains { $0.contains("make-country-outlines.py") },
            "no package.json script runs the outline generator"
        )
    }

    // MARK: - The outline masters (0.8.0, A1; re-based 0.8.4, F1)

    /// Every outline master under `art/icons/entries/countries/`, by stem.
    private static var outlineMasters: Set<String> {
        get throws {
            let dir = repoRoot.appendingPathComponent("art/icons/entries/countries")
            let names = try FileManager.default.contentsOfDirectory(atPath: dir.path)
            return Set(
                names
                    .filter { $0.lowercased().hasSuffix(".png") }
                    .map { String($0.dropLast(4)) }
            )
        }
    }

    /// **Masters drawn ahead of the catalog**, named rather than subtracted.
    ///
    /// The 0.8.4 drop is forty-six countries and states; the catalog names
    /// thirty-three of them. The other thirteen are not clutter and not a
    /// mistake — they are the next thirteen places a region could land in, and
    /// wiring one is a single `COUNTRY_SHAPE_ICONS` row because the art and its
    /// fill colour are already here.
    ///
    /// It is an exemption list in `assertOutlineCoverage`'s sense and fails the
    /// same two ways: a stem here that the catalog starts drawing has to come
    /// out, and a stem here with no master on disk means art was deleted. That
    /// is what stops "drawn ahead" from becoming the excuse that any unused file
    /// in the directory is fine.
    private static let drawnAheadOutlines: Set<String> = [
        "arizona", "bosnia", "czechia", "idaho", "israel", "michigan",
        "missouri", "new-mexico", "serbia", "slovakia", "texas", "ukraine",
        "virginia",
    ]

    /// **Every outline the catalog draws has a master, and every master is
    /// either drawn or on the backlog.**
    ///
    /// This is the same two-way shape `assertOutlineCoverage` uses, one layer
    /// further back. That check asks "does this place have outline art"; this one
    /// asks "does that art exist on disk".
    ///
    /// **It used to check the rings, and 0.8.4 is why it cannot any more.**
    /// Through 0.8.3 every outline was rasterised from
    /// `scripts/country-outline-rings.py`, so "does that art have a master" and
    /// "is there an authored ring" were the same question. F1 replaced the whole
    /// directory with hand-drawn coastlines, which no ring describes — the rings
    /// survive as a fallback rasteriser and are no longer the art. Checking them
    /// now would be asserting a relationship the build does not have.
    ///
    /// The three spellings that made the old version necessary are also gone: a
    /// master's stem *is* its `art:outline-<stem>` id, so `import-class-art.py`
    /// resolves the source by rule and there is no filename table to drift.
    @Test("every drawn outline has a master, and every master is drawn or on the backlog")
    func outlineMastersMatchTheManifest() throws {
        let manifest = try Data(
            contentsOf: Self.repoRoot
                .appendingPathComponent("Sources/VinodexCore/Resources/icons.json")
        )
        let json = try JSONSerialization.jsonObject(with: manifest) as? [String: Any]
        let shapes = json?["countryShapeIcons"] as? [String: String] ?? [:]
        #expect(!shapes.isEmpty, "icons.json carries no countryShapeIcons")

        let wanted = Set(shapes.values.map { $0.replacingOccurrences(of: "art:outline-", with: "") })
        let masters = try Self.outlineMasters
        #expect(masters.count >= 30, "found only \(masters.count) outline masters — is the checkout complete?")

        #expect(
            wanted.subtracting(masters).isEmpty,
            """
            outlines the catalog draws with no master: \
            \(wanted.subtracting(masters).sorted()) — draw them into art/icons/entries/countries/
            """
        )
        #expect(
            masters.subtracting(wanted) == Self.drawnAheadOutlines,
            """
            the drawn-ahead backlog has drifted — \
            unlisted masters nothing draws: \(masters.subtracting(wanted).subtracting(Self.drawnAheadOutlines).sorted()), \
            listed but now drawn or deleted: \(Self.drawnAheadOutlines.subtracting(masters.subtracting(wanted)).sorted())
            """
        )
    }

    /// **Every master has an ink colour, and every ink colour has a master.**
    ///
    /// The masters are silhouettes — one flat cream shape each — and
    /// `import-class-art.py` paints them from `country-outline-fills.py` at
    /// import time (0.8.4, F1). A master with no row would import as a blank
    /// key error at art time on somebody's laptop; a row with no master is a
    /// colour chosen for a country that does not exist here.
    ///
    /// This is the check the fill table could not have before, when it was one
    /// argument to a rasteriser that only ever ran over its own thirty keys.
    @Test("every outline master has a fill colour, and every fill colour a master")
    func everyMasterHasAFill() throws {
        let source = try Self.read("scripts", "country-outline-fills.py")
        guard let table = Self.slice(source, from: "FILL = {", to: "}") else {
            Issue.record("could not parse FILL out of country-outline-fills.py")
            return
        }
        // Alternating stem, "#rrggbb" across the quoted runs.
        let quoted = Self.quoted(table)
        var fills: Set<String> = []
        for pair in stride(from: 0, to: quoted.count - 1, by: 2) {
            fills.insert(quoted[pair])
            #expect(
                quoted[pair + 1].hasPrefix("#") && quoted[pair + 1].count == 7,
                "\(quoted[pair]): '\(quoted[pair + 1])' is not a #rrggbb colour"
            )
        }
        #expect(!fills.isEmpty, "parsed no fill rows")

        let masters = try Self.outlineMasters
        #expect(
            masters.subtracting(fills).isEmpty,
            "outline masters with no fill colour: \(masters.subtracting(fills).sorted())"
        )
        #expect(
            fills.subtracting(masters).isEmpty,
            "fill colours for outlines that do not exist: \(fills.subtracting(masters).sorted())"
        )
    }

    // MARK: - The two hand-mapped drops (0.8.5, F1)
    //
    // `import-stamp-art.py` and `import-sticker-art.py` are the only importers
    // that rename what they copy. Every other one takes the file's own stem,
    // so its output roster is its input roster and there is nothing to get
    // wrong. These two carry a dict from the picture's name to the app's name,
    // because both drops arrived named for what is drawn on them — and a
    // wrong row in either is invisible at runtime: `StampFrame` falls back to
    // an SF Symbol and `SkinStickerView` to the skin emblem, both silently, and
    // neither family is walked by `assertAssetsExist`.
    //
    // So each map is checked at three joints: the source files it claims to
    // read, the stems the app actually asks for, and the PNGs that came out.

    /// A Python `NAME = { "k": "v", ... }` dict, as ordered key/value pairs.
    ///
    /// **Line-wise rather than through `quoted`**, unlike every other reader
    /// here, and the difference is that these two dicts are *commented* — the
    /// rows that needed explaining are exactly the rows that would go wrong
    /// silently, so the comments are load-bearing and cannot be asked to move.
    /// `quoted`'s own note says it does not understand them; running it over a
    /// commented body reads whatever falls out of the alternating quote count,
    /// which is not a parse, it is a coincidence.
    ///
    /// So: start after the `NAME = {` line, stop at the first line beginning
    /// `}`, skip blanks and comment-only lines, and take the two quoted runs
    /// out of each remaining row. A row this cannot read is dropped rather
    /// than guessed at, and the two-way assertions above are what turn a
    /// dropped row into a failure.
    ///
    /// **`isNewline`, not `"\n"`, and this is the trap worth carrying out of
    /// 0.8.5.** These scripts are edited on Windows and land in the checkout
    /// with CRLF endings; Swift treats `"\r\n"` as a *single* grapheme cluster,
    /// so `split(separator: "\n")` does not match it and hands back the entire
    /// file as one line. Nothing throws — the parse simply returns an empty map,
    /// or, if it is stripping comments, everything up to the first `#` in the
    /// file. Both were seen while this test was being written, and neither looks
    /// like an encoding problem from the failure message. `\.isNewline` is true
    /// for the CRLF cluster and for LF, so this reads either.
    private static func pythonMap(_ source: String, named: String) -> [(String, String)] {
        var out: [(String, String)] = []
        var inside = false
        for raw in source.split(whereSeparator: \.isNewline) {
            let line = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            if !inside {
                if line.hasPrefix("\(named) = {") { inside = true }
                continue
            }
            if line.hasPrefix("}") { break }
            if line.isEmpty || line.hasPrefix("#") { continue }
            let runs = quoted(line)
            guard runs.count >= 2 else { continue }
            out.append((runs[0], runs[1]))
        }
        return out
    }

    private static func pngStems(_ components: String...) throws -> Set<String> {
        var url = repoRoot
        for component in components { url.appendPathComponent(component) }
        let names = try FileManager.default.contentsOfDirectory(atPath: url.path)
        return Set(
            names.filter { $0.hasSuffix(".png") }.map { String($0.dropLast(4)) }
        )
    }

    /// Stems the app asks for that nobody has drawn yet (0.8.6, C6).
    ///
    /// **A named backlog, checked both ways**, on the model of
    /// `regionsHaveOutlineArt`: a stem missing from here and from the drop fails
    /// the roster, *and* a stem listed here that has since been drawn fails it
    /// too — so the list cannot quietly become an excuse.
    ///
    /// **Empty since 0.8.7 (A1), and it emptied itself by that second rule.**
    /// It held `stamp-all-grapes` and `stamp-all-styles` for one release: 8.6's
    /// C6 asked for those two badges to take `stamp1.png` and `stamp2.png`, the
    /// names were spent on the two back-plate decals, and the
    /// badges got stems with no art behind them. 0.8.7's item 4 settles the
    /// collision the other way — the badges take the pictures, the two decals
    /// leave the plate — so the gap closed and the two rows came out. That is
    /// the half of the design that stops a backlog rotting into an exemption,
    /// working exactly once, which is the only way to find out that it does.
    ///
    /// Kept rather than deleted: the mechanism is the point, and the next stamp
    /// wired ahead of its art is one row.
    private static let undrawnStampStems: Set<String> = []

    /// **The stamp drop maps every source file onto a stem the app asks for.**
    ///
    /// Eight Passport badges and two back-plate decals, less whatever
    /// `undrawnStampStems` names. `StampCatalog.artStem` and
    /// `BackPlateDecal.artStem` are both in Core, so this compares the Python
    /// against the types themselves rather than against another list.
    @Test("every stamp source maps to a stem the app asks for, and back")
    func stampRosterIsComplete() throws {
        let map = Self.pythonMap(try Self.read("scripts", "import-stamp-art.py"), named: "STEM_FOR")
        #expect(!map.isEmpty, "could not parse STEM_FOR out of import-stamp-art.py")

        let sources = Set(map.map(\.0))
        let onDisk = try Self.pngStems("art", "icons", "chrome", "stamps")
        #expect(
            sources == onDisk,
            """
            import-stamp-art.py and art/icons/chrome/stamps/ disagree — \
            drawn but unmapped (these are skipped at import): \(onDisk.subtracting(sources).sorted()), \
            mapped but not drawn: \(sources.subtracting(onDisk).sorted())
            """
        )

        let produced = Set(map.map(\.1))
        let wanted = Set(StampCatalog.all.map(\.artStem))
            .union(BackPlateDecal.allCases.map(\.artStem))

        // The backlog, both ways. First: everything on it is genuinely something
        // the app asks for — a row naming a stem nothing wants is a typo, and a
        // typo here would hide a real gap.
        #expect(
            Self.undrawnStampStems.isSubset(of: wanted),
            "undrawnStampStems names stems nothing asks for: \(Self.undrawnStampStems.subtracting(wanted).sorted())"
        )
        // Second: nothing on it has quietly been drawn. When it has, this fails
        // and the row comes out — which is the half that stops a backlog rotting
        // into a permanent exemption.
        #expect(
            Self.undrawnStampStems.isDisjoint(with: produced),
            "these are drawn now — delete them from undrawnStampStems: \(Self.undrawnStampStems.intersection(produced).sorted())"
        )

        let expected = wanted.subtracting(Self.undrawnStampStems)
        #expect(
            produced == expected,
            """
            import-stamp-art.py's output stems and the app's disagree — \
            produced but nothing asks for: \(produced.subtracting(expected).sorted()), \
            asked for but not produced: \(expected.subtracting(produced).sorted())
            """
        )

        // And the drop actually landed. This is the joint the other two cannot
        // see: a map that is right about both ends still leaves nothing in the
        // bundle if nobody ran `npm run icons`.
        let bundled = try Self.pngStems("Sources", "VinodexUI", "Resources", "StampArt")
        #expect(
            bundled == expected,
            "Resources/StampArt holds \(bundled.sorted()), the app asks for \(expected.sorted())"
        )
    }

    // MARK: - The two registers added with the 0.8.9 drop (A2/A3)
    //
    // Neither importer renames what it copies — the stem *is* the filename, as
    // it is for buttons, footers, cartridges and marquee glyphs — so there is
    // no map to police the way `STEM_FOR` and `SKIN_FOR` are policed above.
    // What there is instead is a *type* per register, and these two tests hold
    // each type equal to its source directory and to its bundle output. That
    // is the same three-joint shape as the stamp roster, minus the joint that
    // does not exist here.

    /// **The twenty UI glyphs: directory, type and bundle all agree.**
    ///
    /// The joint that matters is the last one. `UIGlyph.unwired` names ten
    /// glyphs no screen asks for yet — eleven until 0.8.9b gave `level5` a rung
    /// — and the temptation with a list like that
    /// is to let it excuse a missing file — so the equality below is over
    /// *every* case, wired or not. A parked glyph must still be drawn and still
    /// be in the bundle; what "parked" means is that no view names it, which is
    /// a fact about `Sources/VinodexUI` and not about this directory.
    @Test("every UI glyph is drawn, typed and bundled")
    func glyphRosterIsComplete() throws {
        let wanted = Set(UIGlyph.allCases.map(\.rawValue))
        #expect(wanted.count == UIGlyph.allCases.count, "two UIGlyph cases share a raw value")

        let onDisk = try Self.pngStems("art", "icons", "chrome", "glyphs")
        #expect(
            onDisk == wanted,
            """
            UIGlyph and art/icons/chrome/glyphs/ disagree — \
            drawn but not typed (these ship nowhere): \(onDisk.subtracting(wanted).sorted()), \
            typed but not drawn: \(wanted.subtracting(onDisk).sorted())
            """
        )

        // `artStem`, restated — the prefix `import-glyph-art.py` writes. Two
        // languages, one expression, held together here exactly as
        // `ChassisSkin.stickerStem` is.
        let expected = Set(UIGlyph.allCases.map(\.artStem))
        let bundled = try Self.pngStems("Sources", "VinodexUI", "Resources", "GlyphArt")
        #expect(
            bundled == expected,
            "Resources/GlyphArt holds \(bundled.sorted()), UIGlyph asks for \(expected.sorted())"
        )

        // The backlog, one way only, because the other way cannot be checked
        // from Core: whether a stem has a call site is a fact about VinodexUI.
        // What *is* checkable is that the list names real glyphs — a typo here
        // would silently shrink the parked set and make a genuine gap look
        // deliberate.
        #expect(
            UIGlyph.unwired.isSubset(of: Set(UIGlyph.allCases)),
            "UIGlyph.unwired names cases that do not exist"
        )
        // And that no tier's shield is on it. This is the half of the ladder
        // wiring a roster can see: `PassportTier.glyph` is exhaustive, so every
        // rung has a shield.
        for tier in PassportTier.allCases {
            #expect(
                !UIGlyph.unwired.contains(tier.glyph),
                "\(tier.displayName) draws \(tier.glyph.artStem), which is parked as unwired"
            )
        }
        // **This line used to read the other way** — `unwired.contains(.level5)`,
        // with the message "level5 has a rung now — take it off the list". It
        // got one in 0.8.9b (WINE MONK), so the assertion flips, which is the
        // whole behaviour a two-way gate is for: the parked list cannot rot into
        // an excuse, because coming *off* it is as checked as going on.
        //
        // All five shields are now spoken for, so the stronger statement is
        // available and worth making: no `level*` glyph is parked at all.
        for glyph in UIGlyph.allCases where glyph.rawValue.hasPrefix("level") {
            #expect(
                !UIGlyph.unwired.contains(glyph),
                "\(glyph.artStem) is parked, but every numbered shield has a rung now"
            )
        }
        #expect(
            Set(PassportTier.allCases.map(\.glyph)).count == PassportTier.allCases.count,
            "two rungs share a shield"
        )
    }

    /// **The six Professor Vino expressions: directory, type and bundle.**
    ///
    /// Written before anything draws them (the presenter is 0.8.9's phase 2),
    /// which is the point rather than an oversight. Art that ships ahead of its
    /// caller is fine; art that ships ahead of its caller *unchecked* is how a
    /// seventh delivered file quietly becomes six bundled ones and nobody finds
    /// out until the screen is built. The seventh here — `profvino.png`, the
    /// contact sheet the six were cut from — lives in `art/icons/reference/`
    /// with the other source sheets and is deliberately outside this equality.
    @Test("every Vino expression is drawn, typed and bundled")
    func vinoRosterIsComplete() throws {
        let wanted = Set(VinoExpression.allCases.map(\.rawValue))
        let onDisk = try Self.pngStems("art", "icons", "chrome", "vino")
        #expect(
            onDisk == wanted,
            """
            VinoExpression and art/icons/chrome/vino/ disagree — \
            drawn but not typed: \(onDisk.subtracting(wanted).sorted()), \
            typed but not drawn: \(wanted.subtracting(onDisk).sorted())
            """
        )

        let expected = Set(VinoExpression.allCases.map(\.artStem))
        let bundled = try Self.pngStems("Sources", "VinodexUI", "Resources", "VinoArt")
        #expect(
            bundled == expected,
            "Resources/VinoArt holds \(bundled.sorted()), VinoExpression asks for \(expected.sorted())"
        )

        // The sheet is a source, not an asset. Asserted rather than assumed:
        // dropping it into `chrome/vino/` would make the importer ship a
        // 1536x1024 PNG of all six faces as if it were a seventh portrait, and
        // the equality above would then fail with a name that explains nothing.
        let sheets = try Self.pngStems("art", "icons", "reference")
        #expect(
            sheets.contains("profvino-sheet"),
            "the Professor Vino contact sheet has left art/icons/reference/"
        )
    }

    /// Every `ChassisSkin` raw value, read out of `DexTheme.swift`.
    ///
    /// Textual because `ChassisSkin` lives in `VinodexUI`, which Linux cannot
    /// compile — the same reason and the same technique `loaderSearchPath` uses
    /// on `PixelArtLoader.subdirectories`. The enum's cases are the only
    /// `case <name> = "<VALUE>"` lines between its declaration and its first
    /// computed property, which is what the slice below takes.
    ///
    /// **The colon in the marker is load-bearing.** `ChassisSkinSection` is
    /// declared thirty-six lines above `ChassisSkin` in the same file, and
    /// `range(of:)` matches a prefix — so "public enum ChassisSkin" found the
    /// *section* enum and this returned its six raw values (FESTIVE, VESSEL,
    /// CLEARTECH, …) with no sign that anything had gone wrong. The count
    /// assertion at the call site is the second guard, and it is the one that
    /// caught it.
    private static var chassisSkinRawValues: Set<String> {
        get throws {
            let text = try read("Sources", "VinodexUI", "DexTheme.swift")
            guard let declaration = text.range(of: "public enum ChassisSkin:") else { return [] }
            let body = text[declaration.upperBound...]
            // The cases run to the first member that is not one.
            let end = body.range(of: "\n    public var")?.lowerBound ?? body.endIndex
            var values: Set<String> = []
            // `isNewline` for the reason `pythonMap` documents at length: a
            // CRLF file is one grapheme-cluster line to `split(separator:)`.
            for line in body[..<end].split(whereSeparator: \.isNewline) {
                let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                guard trimmed.hasPrefix("case "), trimmed.contains(" = \"") else { continue }
                let runs = quoted(trimmed)
                if let value = runs.first { values.insert(value) }
            }
            return values
        }
    }

    /// Shells with no decal drawn, named so the shortfall cannot rot (0.8.5, F1).
    ///
    /// The drop is twenty files against twenty-two shells. These two keep
    /// `SkinEmblem`, which is the documented fallback and looks deliberate — so
    /// without naming them here, "the artist has not got to it" and "somebody
    /// mistyped a rawValue" are the same observation. The list is asserted in
    /// both directions below: a name here that *does* have art fails too, which
    /// is what stopped the outline backlog becoming an excuse in 0.8.4.
    private static let shellsWithoutADecal: Set<String> = ["CHRISTMAS", "ORANGE WINE"]

    /// **Every shell decal maps onto a real shell, and every shell has one or is
    /// named as not having one.**
    @Test("every artifact maps to a chassis skin, and every skin to an artifact")
    func stickerRosterIsComplete() throws {
        let map = Self.pythonMap(try Self.read("scripts", "import-sticker-art.py"), named: "SKIN_FOR")
        #expect(!map.isEmpty, "could not parse SKIN_FOR out of import-sticker-art.py")

        let sources = Set(map.map(\.0))
        let onDisk = try Self.pngStems("art", "icons", "chrome", "stickers")
        #expect(
            sources == onDisk,
            """
            import-sticker-art.py and art/icons/chrome/stickers/ disagree — \
            drawn but unmapped (these are skipped at import): \(onDisk.subtracting(sources).sorted()), \
            mapped but not drawn: \(sources.subtracting(onDisk).sorted())
            """
        )

        let skins = try Self.chassisSkinRawValues
        #expect(skins.count >= 20, "parsed only \(skins.count) ChassisSkin cases — did the slice hold?")
        let claimed = Set(map.map(\.1))
        #expect(
            claimed.subtracting(skins).isEmpty,
            "decals mapped to no such shell: \(claimed.subtracting(skins).sorted())"
        )
        #expect(
            skins.subtracting(claimed) == Self.shellsWithoutADecal,
            """
            the undrawn-shell list is out of date — \
            no decal and not named: \(skins.subtracting(claimed).subtracting(Self.shellsWithoutADecal).sorted()), \
            named but now drawn: \(Self.shellsWithoutADecal.subtracting(skins.subtracting(claimed)).sorted())
            """
        )

        // `ChassisSkin.stickerStem`, restated — kebab-cased raw value under the
        // `sticker-` prefix. Two languages, one expression; this is the joint
        // where they are held together.
        let expected = Set(claimed.map { "sticker-" + $0.lowercased().replacingOccurrences(of: " ", with: "-") })
        let bundled = try Self.pngStems("Sources", "VinodexUI", "Resources", "StickerArt")
        #expect(
            bundled == expected,
            "Resources/StickerArt holds \(bundled.sorted()), the skins ask for \(expected.sorted())"
        )
    }
}
