#!/usr/bin/env bash
# Regenerate Vinodex.xcodeproj from project.yml — the one entry point for the
# Mac/Xcode build path. The project file is gitignored; this script is how it
# comes to exist on a fresh clone:
#
#   brew install xcodegen        # once
#   scripts/generate-xcodeproj.sh
#   open Vinodex.xcodeproj       # or xcodebuild -scheme Vinodex ...
#
# Version stamping (the thing xtool 1.17 gets wrong — it hardcodes 1.0.0/1):
#   MARKETING_VERSION        <- newest annotated tag, `v` stripped (v0.9.2 -> 0.9.2).
#                               Tags are the version of record; see README "Deploying".
#   CURRENT_PROJECT_VERSION  <- `git rev-list --count HEAD`. Monotonic per branch,
#                               unique per commit — TestFlight rejects duplicate
#                               (version, build) pairs, so never reuse a build
#                               number for a re-upload: commit first.
#
# Both land in App/Version.generated.xcconfig (gitignored), which project.yml
# points every configuration at. Xcode's Info.plist preprocessing does the rest.
set -euo pipefail

cd "$(dirname "$0")/.."

TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)"
MARKETING_VERSION="${TAG#v}"
CURRENT_PROJECT_VERSION="$(git rev-list --count HEAD)"

# The firmware gate (0.9.54, release-readiness A2's second half). The tag is
# the version of record, but the FIRMWARE screen tells the user what build
# they run from firmware.json's head entry — and an archive cut from a tag
# whose firmware entry was never written ships a device that lies about
# itself. `AppVersion` defused the 1.0-placeholder half of this trap in code;
# this is the half only the build path can see. Deliberately a hard stop and
# not a warning: the fix is one firmware entry, and the alternative shipped.
FIRMWARE_HEAD="$(python3 -c "
import json
print(json.load(open('Sources/VinodexCore/Resources/firmware.json'))['version'])
")"
if [ "${TAG}" != "v0.0.0" ] && [ "${FIRMWARE_HEAD}" != "${MARKETING_VERSION}" ]; then
    echo "ERROR: tag says ${MARKETING_VERSION} but firmware.json's head entry is ${FIRMWARE_HEAD}." >&2
    echo "Write the ${MARKETING_VERSION} entry in shared/firmware.ts, regenerate, commit — then re-tag/archive." >&2
    exit 1
fi

mkdir -p App
cat > App/Version.generated.xcconfig <<EOF
// Generated by scripts/generate-xcodeproj.sh — do not edit, do not commit.
// ${TAG} @ $(git rev-parse --short HEAD)
MARKETING_VERSION = ${MARKETING_VERSION}
CURRENT_PROJECT_VERSION = ${CURRENT_PROJECT_VERSION}
EOF

echo "version ${MARKETING_VERSION} build ${CURRENT_PROJECT_VERSION}"
xcodegen generate
